name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    GO_VERSION: "~1.20"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Unit Test
        run: make test

      # - name: Fmt Test
      #   run: fmtFiles=$(make fmt); if [ "$fmtFiles" != "" ];then exit 1; fi

